### ISSUE TITLE
Crashing with Improved Streaming

### ISSUE THREAD

**Issue by elcascavel** [JuniorDjjr/PedsExtender#1]
Will you ever update this mod? It's pretty good but if you have IS installed it'll consistently crash when adding additional cops. I haven't tested with other ped types.

**Comment by JuniorDjjr** [comment]
Send the CrashInfo log.

**Comment by elcascavel** [comment]
I no longer get crashes for some reason but two of my friends do. Here's the crash log:

```
GTA SA 1.0.0.0 US
Unhandled exception at 0x00749B7B in gta-sa.exe (+0x349b7b): 0xC0000005: Access violation reading location 0x00000008.
    Register dump:
        EAX: 0x00000000  EBX: 0x00000000  ECX: 0x00000000  EDX: 0x7A5E7C6C  
        EDI: 0x00000008  ESI: 0x00000000  EBP: 0x00000000  EIP: 0x00749B7B  
        ESP: 0x0177EF70  EFL: 0x00210246  CS: 0x00000023   SS: 0x0000002B   
        GS: 0x0000002B   FS: 0x00000053   ES: 0x0000002B   DS: 0x0000002B   
        
    Stack dump:
        0x0177EF70:  00000000 00000000 00000000 00000000 0073483D 00000000
        0x0177EF88:  00734810 0177EF90 00000000 004D672B 00000000 17F1B3BC
        0x0177EFA0:  005E489E 00000000 00000000 17F1B3BC 005DDCB5 00003070
        0x0177EFB8:  00000000 00000006 00000006 17F1B3BC 0177F018 0083D788
        0x0177EFD0:  00000000 00612834 00000000 00000000 00000006 00000001
        0x0177EFE8:  00B6F028 00420C74 0177F004 0177F004 00000001 00B6FA74
        0x0177F000:  00B6F028 41F6C040 420C5DA8 40924FF8 00420D5B 0177F05C
        0x0177F018:  0177F168 0083EE28 00000001 006153B0 17F1B3BC 00000000
        0x0177F030:  0177F05C 00000001 00000000 00000004 0177F224 00000001
        0x0177F048:  0177F0B8 423179E9 0D0C7480 00000001 00000001 450878B4
        base: 0x01580000   top: 0x0177EF70   bottom: 0x01780000
        
    Backtrace (may be wrong):
        =>0x00749B7B _RpClumpForAllAtomics+0xb in gta-sa.exe (+0x349b7b) 
```

**Comment by JuniorDjjr** [comment]
Are you sure the cop is installed correctly? Did you check CrashInfo?

**Comment by elcascavel** [comment]
![image](https://github.com/user-attachments/assets/97e5aae0-0ffc-4347-8ea4-d0ff8e0ca741)

Here's how I added the new cop:
- Created a new ped, named it `lapd2`. Put it into modloader like the rest of my other peds.

Added this line to my peds.ide
`12400, LAPD2, LAPD2, COP, STAT_COP, busywoman, 1FFF, 0, null, 9,9, PED_TYPE_EMG,VOICE_GEN_SBFYST ,VOICE_GEN_SBFYST`

Also restored a bunch of unused peds similar to your other mod:
`283, csher, csher, COP, STAT_COP, swat, 1FFF, 0, null, 9,9, PED_TYPE_EMG,VOICE_EMG_RCOP1 ,VOICE_EMG_RCOP4`
`269, CDEPUT, CDEPUT, COP, STAT_COP, swat, 1FFF, 0, null, 9, 9, PED_TYPE_EMG, VOICE_EMG_RCOP1, VOICE_EMG_RCOP4`

I've noticed that the lapd2 cops do not speak, they're completely mute. Not sure if it's a problem with the mod or my configuration but I literally copied those settings from another female ped.

I'm making a total conversion mod and I'd be happy to share the complete files if you want to debug this further. To my knowledge, no other mods are causing the crashing. My Discord is elcascavel

**Comment by JuniorDjjr** [comment]
And how do you know that is installed and working correctly is this is issue with PedsExtender e not with your game/installation?

**Comment by elcascavel** [comment]
I played the game every time I added a new mod and never crashed until I put in Peds Extender. It never crashes if I remove Improved Streaming. Surely it can't be a coincidence?

**Comment by JuniorDjjr** [comment]
Disable the "Range3" (pedestrians) from ini to see if fixes it.

**Comment by elcascavel** [comment]
Sorry for the delay. Disabling it does not seem to solve any crashing. This seems to occur quite frequently when in a new game or after loading a save. The only solution I've found for the crashing is simply removing Peds Extender which is not what we want. In fact, I personally had no crashing until I saved the game. After that, whether I start a new or load into a save game it crashes consistently again.

Not sure if this is relevant but here's the Peds Extender log.

```
v1.1.4 by Junior_Djjr - MixMods.com.br
Trying to find army
Model found army
Trying to find cdeput
Model found cdeput
Trying to find dsher
Model found dsher
Trying to find sfpdm1
Model found sfpdm1
Trying to find lvpdm1
Model found lvpdm1
Trying to find cspdm1
Trying to find dspdm1
Trying to find wmycd2
Trying to find wmyskat
Trying to find poolgy2
Trying to find sktbd
Trying to find lapd2
Model found lapd2
Trying to find lapd3
Trying to find sfpd2
Trying to find lvpd2
Trying to find csher1
Trying to find dsher1
Ok
```

There's also the issue of my added female officer not having any voices, despite giving the model one in peds.ide.

With Model Variations this crashing does not occur. I'd prefer to use Peds Extender as I think it's much easier to set up. It'd be a shame to continue crashing as this is very useful for the [mod](https://www.youtube.com/watch?v=mBtEPY3H2qI) we're making.

**Comment by JuniorDjjr** [comment]
ID 1573 works, but 1699+ doesn't.

I think I fixed it, I updated the mod, check it: https://sharemods.com/pfge1km3wdw3/SA_-_Peds_Extender.7z.html

**Comment by elcascavel** [comment]
This seems to have fixed the issue, I'm no longer experiencing crashes. Muito obrigado!

**Comment by JuniorDjjr** [comment]
Nice, I updated on MixMods, and soon I'll share the update with some other mods too.
